//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';
import {BaseDto} from 'ws-request-hook';

export interface ClientAnswersQuestionDto extends BaseDto {
    answer?: string;
    roomId?: string;
}

export interface GameState extends BaseDto {
    players?: Player[];
    currentQuestion?: Question;
    scores?: { [key: string]: number; };
    phase?: string;
    timeLeft?: number;
    correctAnswer?: string;
}

export interface Player extends BaseDto {
    id?: string;
    nickName?: string;
    score?: number;
}

export interface Question extends BaseDto {
    id?: string;
    questionText?: string;
    options?: string[];
}

export interface ClientWantsToAuthenticateDto extends BaseDto {
    username?: string;
}

export interface ClientWantsToSubscribeToTopicDto extends BaseDto {
    topicId?: string;
}

export interface ClientWantsToUnsubscribeFromTopicDto extends BaseDto {
    topicId?: string;
}

export interface ServerAuthenticatesClientDto extends BaseDto {
    topics?: string[];
}

export interface ServerConfirmsDto extends BaseDto {
    success?: boolean;
}

export interface ServerSendsErrorMessageDto extends BaseDto {
    error?: string;
}

/** Available eventType constants */
export enum StringConstants {
    ClientAnswersQuestionDto = "ClientAnswersQuestionDto",
    GameState = "GameState",
    Player = "Player",
    Question = "Question",
    ClientWantsToAuthenticateDto = "ClientWantsToAuthenticateDto",
    ClientWantsToSubscribeToTopicDto = "ClientWantsToSubscribeToTopicDto",
    ClientWantsToUnsubscribeFromTopicDto = "ClientWantsToUnsubscribeFromTopicDto",
    ServerAuthenticatesClientDto = "ServerAuthenticatesClientDto",
    ServerConfirmsDto = "ServerConfirmsDto",
    ServerSendsErrorMessageDto = "ServerSendsErrorMessageDto",
}

